# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Release App
on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:

  testjob:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        set -v
        python3 -V
        python3 -m pip install --upgrade pip build virtualenv PyInstaller
        python3 -m virtualenv venv
        source venv/bin/activate
        python -m pip install setuptools_scm
        python -m setuptools_scm
        git describe --all
        #git describe
        git show
        git log

    
    